In [5]:
import numpy as np

In [6]:
n = np.array((1,2,3))
print(n)

[1 2 3]


In [7]:
print(type(n))

<class 'numpy.ndarray'>


In [20]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(type(arr))

<class 'numpy.ndarray'>


In [17]:
print(arr.ndim)

2


In [18]:
print(arr.shape)

(3, 3)


In [21]:
print(arr.size)

9


In [22]:
print(arr.dtype)

int64


In [37]:
arr=np.array([[1,2],[3,4],[5,6]])
print(arr)
flat=arr.flatten()
print(flat)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [38]:
new_arr=arr.reshape(6,1,1)
print(new_arr)
flat=arr.flatten()
print(flat)

[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]]
[1 2 3 4 5 6]


In [36]:
arr=np.array([[1,2,3],[4,5,6]])
flat_arr=arr.flatten()

print(arr)
print(flat_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
